@host=https://localhost:5000/api
@adminAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lZXQudGhha2FyQGdsc3VuaXZlcnNpdHkuYWMuaW4iLCJVc2VySWQiOiIxIiwiVG9rZW5UeXBlIjoiQWNjZXNzVG9rZW4iLCJyb2xlIjoiQWRtaW4iLCJQZXJtaXNzaW9uIjoiQWxsIiwibmJmIjoxNzU1MTEyMDkwLCJleHAiOjIwNzA2NDQ5MDksImlhdCI6MTc1NTExMjA5MCwiaXNzIjoibG9jYWxob3N0In0.H-dn4wwHmFytO7R16Bv-tRD3JMJqq3ks7DtZrOgtht0
